// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xiqjwzpwvgxnakosfiha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhpcWp3enB3dmd4bmFrb3NmaWhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzExNTE4NTcsImV4cCI6MjA0NjcyNzg1N30.8dwJx5SyRHl1PU4c-6dc3y-ulb34Ek6fzl4nvNRyS9g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);